on: [push]

jobs:
  local-server-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Run tests against local server
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Start Local Server
        run: npm start &
        shell: bash

      # Wait for the server to start. Adjust the sleep time as needed.
      - name: Wait for Server to be Ready
        run: sleep 10

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Here we run the Playwright tests against the local server
      - name: Run Playwright tests
        run: URL=http://localhost:3000 npx playwright test
        env:
            DEPLOYMENT_URL: http://localhost:3000

      - uses: actions/upload-artifact@v3
        if: always()
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
